---
- name: Create new resource policy in Azure
  hosts: localhost
  # become: true

  vars:
    local_repo_dir: "/tmp/aaa"

  vars_prompt:

    - name: policy_ev
      prompt: Choose an environment between dev and prod
      private: false

    - name: policy_name
      prompt: New policy name
      private: false

    - name: policy_description
      prompt: Summary of the policy rule
      private: false

    - name: policy_rule
      prompt: JSON Object representing the new policy rule
      private: false

# clone terraform-plan 
# add policy block in the xxx.policies.tfvars
# add policy rule in the az-rg-policies folder


  tasks:
    - name: Fetch git repository
      ansible.builtin.git:
        repo: "https://github.com/Red-Hat-Demo-Use-Cases/demo-aap-terraform-integration.git"
        dest: "{{ local_repo_dir }}"
        clone: true
        force: true


    - name: Add string in file
      ansible.builtin.blockinfile:
        path: "{{ local_repo_dir }}/terraform-plan/{{ policy_ev }}.policies.tfvars"
        insertbefore: "## DYNAMIC-INSERT"
        block: |
                Hello
                Hello,


  # tasks:
  #   - name: Write debug message
  #     ansible.builtin.debug:
  #       msg: "Generate {{ policy_name }}"
